# Generated by Django 3.2.9 on 2021-11-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0002_auto_20211124_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='desc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
