# Generated by Django 3.2.9 on 2021-11-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0003_auto_20211126_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
