# Generated by Django 3.2.9 on 2021-12-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0004_auto_20211126_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='pagecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='passwordprotected',
            field=models.BooleanField(default=False),
        ),
    ]
