# Generated by Django 3.2.9 on 2021-12-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0005_auto_20211201_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='passwordprotected',
            field=models.BooleanField(blank=True),
        ),
    ]
