# Generated by Django 3.2.9 on 2021-12-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0006_alter_uploadfile_passwordprotected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='passwordprotected',
            field=models.BooleanField(default=False),
        ),
    ]
