# Generated by Django 3.2.9 on 2021-12-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0007_auto_20211201_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='xmltext',
            field=models.TextField(blank=True),
        ),
    ]
