# Generated by Django 3.2.9 on 2021-12-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0008_uploadfile_xmltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='xmlfile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
