# Generated by Django 3.2.9 on 2021-12-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0009_uploadfile_xmlfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='idno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
