# Generated by Django 3.2.9 on 2021-12-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0010_auto_20211208_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='xmltext',
        ),
    ]
