# Generated by Django 3.2.9 on 2021-12-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0011_remove_uploadfile_xmltext'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadxmlfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('desc', models.CharField(blank=True, max_length=100)),
                ('xmlfile', models.FileField(blank=True, upload_to='')),
                ('pagecount', models.IntegerField(default=0)),
                ('passwordprotected', models.BooleanField(default=False)),
                ('idno', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='idno',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='password',
        ),
    ]
