# Generated by Django 3.2.9 on 2022-01-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0012_auto_20211215_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='xmlfile',
        ),
        migrations.RemoveField(
            model_name='uploadxmlfile',
            name='pagecount',
        ),
        migrations.RemoveField(
            model_name='uploadxmlfile',
            name='passwordprotected',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='isPageCountChecked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='isPdfFileUploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='isPdfSaved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadxmlfile',
            name='isXmlFileUploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadxmlfile',
            name='xmlEmailParseCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadxmlfile',
            name='xmlNameParseCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadxmlfile',
            name='xmlPasswordParseCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
