# Generated by Django 3.2.9 on 2022-01-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0014_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='PageLimitExceeded',
            field=models.BooleanField(default=False),
        ),
    ]
