# Generated by Django 3.2.9 on 2022-01-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0015_uploadfile_pagelimitexceeded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'get_latest_by': ['pagelimit']},
        ),
    ]
