# Generated by Django 3.2.9 on 2022-03-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0016_alter_configuration_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadcsvfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('desc', models.CharField(blank=True, max_length=100)),
                ('csvfile', models.FileField(blank=True, upload_to='')),
                ('isXmlFileUploaded', models.BooleanField(default=False)),
            ],
        ),
    ]
