# Generated by Django 3.2.9 on 2022-03-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0017_uploadcsvfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadcsvfile',
            old_name='isXmlFileUploaded',
            new_name='isCsvFileUploaded',
        ),
    ]
